controller_joint_names: ['left_wheel_joint', 'right_wheel_joint', 'vertical_castor_joint', 'horizontal_castor_joint', ]

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 'left_wheel_joint'
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 'right_wheel_joint'
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: 'vertical_castor_joint'
    pid: {p: 100.0, i: 0.01, d: 10.0}
joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: 'horizontal_castor_joint'
    pid: {p: 100.0, i: 0.01, d: 10.0}

    